# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: dark_cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 15 # column width relative to the terminal window
    min_width: 10 # minimum column width as number of characters
  comment:
    color: yellow
    width_percentage: 50
    min_width: 45
  snippet:
    color: grey

finder:
  command: fzf # equivalent to the --finder option
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

# search:
# tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: zsh # shell used for shell out. possible values: bash, zsh, dash, ...
  finder_command: zsh # similar, but for fzf's internals